remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Mi perfil de github
description: Un lugar donde podrás aprender lenguajes de programación y colaborar con nuevo conocimiento
show_downloads: true
theme: jekyll-theme-cayman