FILENAME web URL "https://covid.ourworldindata.org/data/owid-covid-data.csv";
DATA covid(LABEL = "Datos de covid, obtenidos de Our World in Data");
INFILE web FIRSTOBS = 2 DLM = "," MISSOVER DSD;
ATTRIB
iso_code length = $4 label = "Código ISO" 
continent length = $12 label = "Continente" 
location length = $24 label = "País" 
date informat = yymmdd10. format = date10. label = "Fecha" 
total_cases label = ""
new_cases label = ""
new_cases_smoothed label = ""
total_deaths label = ""
new_deaths label = ""
new_deaths_smoothed label = ""
total_cases_per_million label = ""
new_cases_per_million label = ""
new_cases_smoothed_per_million label = ""
total_deaths_per_million label = ""
new_deaths_per_million label = ""
new_deaths_smoothed_per_million label = ""
reproduction_rate label = ""
icu_patients label = ""
icu_patients_per_million label = ""
hosp_patients label = ""
hosp_patients_per_million label = ""
weekly_icu_admissions label = ""
weekly_icu_admis_per_million label = ""
weekly_hosp_admis label = ""
weekly_hosp_admis_per_million label = ""
new_tests label = ""
total_tests label = ""
total_tests_per_thousand label = ""
new_tests_per_thousand label = ""
new_tests_smoothed label = ""
new_tests_smoothed_per_thousand label = ""
positive_rate label = ""
tests_per_case label = ""
tests_units length = $18 label = ""
total_vaccinations label = ""
people_vaccinated label = ""
people_fully_vaccinated label = ""
new_vaccinations label = ""
new_vaccinations_smoothed label = ""
total_vaccs_per_hundred label = ""
people_vaccinated_per_hundred label = ""
people_fully_vacc_per_hundred label = ""
new_vaccis_smoothed_per_million label = ""
stringency_index label = ""
population label = ""
population_density label = ""
median_age label = ""
aged_65_older label = ""
aged_70_older label = ""
gdp_per_capita label = ""
extreme_poverty label = ""
cardiovasc_death_rate label = ""
diabetes_prevalence label = ""
female_smokers label = ""
male_smokers label = ""
handwashing_facilities label = ""
hospital_beds_per_thousand label = ""
life_expectancy label = ""
human_development_index label = ""
excess_mortality label = "";
input iso_code -- excess_mortality;
RUN;
